---
- name: Create data volume for Bitbucket's Postgres
  docker_volume:
    name: bitbucket-db-data

- name: Pull Postgres Docker image
  docker_image:
    name: postgres:10.12
    source: pull

- name: Create Postgres container for Bitbucket
  docker_container:
    name: bitbucketdb
    image: postgres:10.12
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - bitbucketdb
    env:
      POSTGRES_USER: "{{ bitbucket_db_user }}"
      POSTGRES_PASSWORD: "{{ bitbucket_db_pass }}"
      POSTGRES_DB: "{{ bitbucket_db_name }}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - bitbucket-db-data:/var/lib/postgresql/data

- name: Create data volume for Bitbucket
  docker_volume:
    name: bitbucket-data
      
- name: Pull Bitbucket Docker image
  docker_image:
    name: atlassian/bitbucket-server:7.4
    source: pull

- name: Create Bitbucket Server Docker container
  docker_container:
    name: bitbucket
    image: atlassian/bitbucket-server:7.4
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - bitbucket
    env:
      SERVER_SECURE: "true"
      SERVER_SCHEME: "https"
      SERVER_PROXY_PORT: "443"
      SERVER_PROXY_NAME: "bitbucket.{{ domain }}"
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    labels:
      traefik.enable: "true"
      traefik.http.routers.bitbucket.rule: "Host(`bitbucket.{{ domain }}`)"
      traefik.http.routers.bitbucket.tls.certresolver: "letsEncrypt"
      traefik.http.routers.bitbucket.entrypoints: "websecure"
      traefik.http.routers.bitbucket.service: "bitbucket"
      traefik.http.services.bitbucket.loadbalancer.server.port: "7990"