---
- name: Create an administrator account
  user:
    name: admin
    password: "{{ admin_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups:
      - sudo
    append: yes

- name: Set authorized key for administrator account 
  authorized_key:
    user: admin
    state: present
    key: "{{ lookup('file', 'files/admin_key.pub') }}"
