---
- name: Create data volume for Jenkins
  docker_volume:
    name: jenkins-data

- name: Pull Jenkins Docker image
  docker_image:
    name: jenkins/jenkins:2.233
    source: pull

- name: Create Jenkins Docker container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:2.233
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - jenkins
    purge_networks: yes
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    labels:
      traefik.enable: "true"
      traefik.http.routers.jenkins.rule: "Host(`jenkins.{{ domain }}`)"
      traefik.http.routers.jenkins.tls.certresolver: "letsEncrypt"
      traefik.http.routers.jenkins.entrypoints: "websecure"
      traefik.http.routers.jenkins.service: "jenkins"
      traefik.http.services.jenkins.loadbalancer.server.port: "8080"